Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "rizkypanji6483/ubuntu22.04"
    vm1.vm.hostname = "kafka-node1"
    vm1.vm.provider "hyperv" do |hv|
      hv.vmname = "kafka-node1"
      hv.cpus = 2
      hv.memory = "2048"
    end
    # Specify the external virtual switch name
    vm1.vm.network :public_network, bridge: 'External Switch'

    # Disable SMB shared folders
    vm1.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "rizkypanji6483/ubuntu22.04"
    vm2.vm.hostname = "kafka-node2"
    vm2.vm.provider "hyperv" do |hv|
      hv.vmname = "kafka-node2"
      hv.cpus = 2
      hv.memory = "2048"
    end
    # Specify the external virtual switch name
    vm2.vm.network :public_network, bridge: 'External Switch'

    # Disable SMB shared folders
    vm2.vm.synced_folder '.', '/vagrant', disabled: true
  end
end

